Resources:
  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.DataTableName}
      AttributeDefinitions:
        - AttributeName: dataKey
          AttributeType: S
        - AttributeName: sKey
          AttributeType: S
      KeySchema:
        - AttributeName: dataKey
          KeyType: HASH
        - AttributeName: sKey
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: validUntil
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: sKey
              KeyType: HASH
            - AttributeName: dataKey
              KeyType: RANGE
          Projection:
            ProjectionType: ALL