Resources:
  bodyOnly:
    Type: 'AWS::ApiGateway::RequestValidator'
    Properties:
      Name: 'body-only'
      RestApiId:
        Ref: ApiGatewayRestApi
      ValidateRequestBody: true
      ValidateRequestParameters: false
  paramsOnly:
    Type: 'AWS::ApiGateway::RequestValidator'
    Properties:
      Name: 'params-only'
      RestApiId:
        Ref: ApiGatewayRestApi
      ValidateRequestBody: false
      ValidateRequestParameters: true
